version: "3"
services:

   jenkins:
       container_name: jenkins
       image: jenkins_ansible
       build:
            context: jenkins_ansible   
       ports:
          - "8090:8080"
       volumes:
          - "$PWD/jenkins_home:/var/jenkins_home"
       networks:
          - net

   remote_host: 
       container_name: remote_host
       image: remote_host
       build:
            context: centos    
       networks:
          - net
   db_host:
       container_name: db
       image: mysql:latest
       environment: 
          - "MYSQL_ROOT_PASSWORD=1234"
       volumes:
          - "$PWD/db_data:/var/lib/mysql"
       networks:
          - net       
networks:
  net:      

